# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: osn_cli/pb/service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from osn_cli.pb import event_pb2 as osn__cli_dot_pb_dot_event__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='osn_cli/pb/service.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x18osn_cli/pb/service.proto\x1a\x16osn_cli/pb/event.proto2\xc2\x01\n\x07Service\x12+\n\x08\x41\x64\x64\x45vent\x12\x0f.events.RawData\x1a\n.events.ID(\x01\x30\x01\x12\x33\n\tListEvent\x12\x15.events.SearchRequest\x1a\r.events.Event0\x01\x12%\n\x08GetEvent\x12\n.events.ID\x1a\r.events.Event\x12.\n\x0fGetEventRawData\x12\n.events.ID\x1a\x0f.events.RawDatab\x06proto3')
  ,
  dependencies=[osn__cli_dot_pb_dot_event__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SERVICE = _descriptor.ServiceDescriptor(
  name='Service',
  full_name='Service',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=53,
  serialized_end=247,
  methods=[
  _descriptor.MethodDescriptor(
    name='AddEvent',
    full_name='Service.AddEvent',
    index=0,
    containing_service=None,
    input_type=osn__cli_dot_pb_dot_event__pb2._RAWDATA,
    output_type=osn__cli_dot_pb_dot_event__pb2._ID,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ListEvent',
    full_name='Service.ListEvent',
    index=1,
    containing_service=None,
    input_type=osn__cli_dot_pb_dot_event__pb2._SEARCHREQUEST,
    output_type=osn__cli_dot_pb_dot_event__pb2._EVENT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEvent',
    full_name='Service.GetEvent',
    index=2,
    containing_service=None,
    input_type=osn__cli_dot_pb_dot_event__pb2._ID,
    output_type=osn__cli_dot_pb_dot_event__pb2._EVENT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetEventRawData',
    full_name='Service.GetEventRawData',
    index=3,
    containing_service=None,
    input_type=osn__cli_dot_pb_dot_event__pb2._ID,
    output_type=osn__cli_dot_pb_dot_event__pb2._RAWDATA,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SERVICE)

DESCRIPTOR.services_by_name['Service'] = _SERVICE

# @@protoc_insertion_point(module_scope)
